[devshell]
name = "dev-web-2022"

[[commands]]
name = "mdbook"
package = "mdbook"

[[commands]]
name = "npm"
category = "Node"
help = "The NodeJS package manager"
package = "nodejs-16_x"

[[commands]]
name = "node"
category = "Node"
package = "nodejs-16_x"

[[commands]]
name = "plantuml"
package = "plantuml"

[[commands]]
name = "graphviz"
package = "graphviz"

[[commands]]
name = "build"
category = "Node"
help = "Build the React frontend and typescript files"
command = "npm run build"

[[commands]]
name = "watch"
category = "Node"
help = "Continuously rebuild the React frontend and typescript files"
command = "npm run watch"

[[commands]]
name = "serve"
category = "Node"
help = "Serve the website"
command = "npm run serve"

[[commands]]
name = "dev"
category = "Node"
help = "Start continuous rebuild and serve the website"
command = "npm run dev"

[devshell.startup.mdbook-completions]
text = '''
mkdir -p "$PRJ_DATA_DIR"/bash-completions
mdbook completions bash > "$PRJ_DATA_DIR"/bash-completions/mdbook
source "$PRJ_DATA_DIR"/bash-completions/mdbook
'''

[devshell.startup.install-node-deps]
text = 'npm install --prefix "$PRJ_ROOT"'

[devshell.startup.add-node-bin-to-path]
text = '''
for node_bin_path in $(fd bin -t d "$PRJ_ROOT"/node_modules/); do
  export PATH="${PATH:+$PATH:}$node_bin_path"
done
'''
