name: deploy

on:
  push:
    branches:
      - Develop

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: '54.37.12.177'
          username: 'gaetan'
          password: 'tu ne PA55 pas !'
          port: 50501
          script: cd ~/dev3/Projet-Dev3 && git fetch && git stash && git pull && cd ~/dev3/Projet-Dev3/web && npm start && cd ~/dev3/Projet-Dev3/API && node app.js
