on:
  push:
    branches:
      - Develop

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: '54.37.12.177'
          username: 'gaetan'
          password: 'tu ne PA55 pas !'
          port: 50501
          continue-on-error: true
          script:  git fetch origin && git reset --hard Develop & cd ~/dev3/Projet-Dev3/API && node app.js & cd ~/dev3/Projet-Dev3/web && npm install && npm start
