on:
  push:
    branches:
      - Develop

jobs:
  deploy:
    runs-on: [ubuntu-latest]

          
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: '21'
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: '54.37.12.177'
          username: 'gaetan'
          password: 'tu ne PA55 pas !'
          port: 50501
          continue-on-error: true
          script: cd ~/dev3 && sh update.sh 
